### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#456] opened 2017-07-24 11:47 UTC
Single Player MC-1.12, Cyclic 1.7.0

Crash on startup, Tested without Cyclic and then it doesn't crash.

[Crashreport](https://pastebin.com/6NWzYbik).

**Comment by Ash70** [comment] 2017-07-24 15:22
Just noticed this might be the same as #453 ?

**Comment by OrdinatorStouff** [comment] 2017-07-25 07:12
Same thing on ATC -- forge 2424 and 2420 same error. cyclic 1.7.0
https://pastebin.com/j8Lrbxgg

**Comment by PrinceOfAmber** [comment] 2017-07-26 02:19
yep duplicate of #453 . conflict is because poison is already added by biomes o plenty first, and then im adding a recipe for a Poison Bucket in an **unsafe** way.  Fix coming soon in 1.7.1

**Closed by PrinceOfAmber** 2017-07-26 02:19 UTC
