### ISSUE TITLE
Uncrafter not consuming item, dupe.

### ISSUE THREAD

**Issue by Snappiestjack** [PrinceOfAmber/Cyclic#1735] opened 2021-01-29 10:58 UTC
Minecraft Version: 1.16.4

Forge Version: 35.1.36

Mod Version: 1.16.5-1.1.4

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):
Uncrafter no longer consumes item when (new cooldown) has expired and item has been uncrafted. Cannot remove item manually.

Log file link:

Video/images/gifs (direct upload or link): 

![2021-01-29_10 55 19](https://user-images.githubusercontent.com/6187142/106266879-dcee1c80-6220-11eb-9f2c-8a7221ddf5a9.png)

**Comment by BlueAgent** [comment] 2021-01-29 11:37
Duplicate of https://github.com/Lothrazar/Cyclic/issues/1727 it'll be fixed in the next release.

**Closed as completed** 2021-02-01 01:31 UTC
Labels: indev, 1.16
