### ISSUE TITLE
Ender library duping books

### ISSUE THREAD

**Issue by krisavi** [PrinceOfAmber/Cyclic#1457] opened 2020-07-22 02:12 UTC
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: Cyclic-1.12.2-1.20.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

When I take a enchanted book with stack size of 1 and right click on ender library, then it gives me message: "Enchanted books must be stack size of 1 to store" and makes the book from stack size of 1 into stack size of 2. effectively duping the enchant. 

Thought to use hopper system as workaround, but it just seems to void the books and enchants on them.

**Comment by luna-system** [comment] 2020-08-05 03:06
Can confirm the same is happening in Enigmatica 2: Expert. Cyclic is 1.20.2, and it looks like neither of the newer versions available are noted as having a fix for this particular issue. I tried using EnderIO item conduits to feed into and out of the Library, but it appeared to be voiding the enchantment and returning a vanilla book.

**Comment by Lothrazar** [comment] 2020-08-23 23:12
Do you have a mod that changes enchanting coremod or sizes or anything? Im in latest made a video. Expected result for library is to find a nearby shelf to put it into. if no shelves available. 

Recorded me using it as well as using hoppers . not very many other mods 
![1457](https://user-images.githubusercontent.com/621529/90991087-622b2200-e55b-11ea-826b-6ae7c24a715e.gif)

**Comment by Lothrazar** [comment] 2020-10-21 04:35
seems to work as intended 1.20.7. if still happening we can take a new in issue in that version, and with modpack details if any

**Closed as completed by Lothrazar** 2020-10-21 04:35 UTC
Labels: cannot replicate, 1.12
