### ISSUE TITLE
[Suggestion] Player Head drop on Player PvP-Kill

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#530] opened 2017-10-06 23:34 UTC
I'd like to have an Option that allows the Players do drop a Player head of themselves on death, when slain by another Player. Kind of an trophy. Headcrumbs did something like that before, but is unfortunatley not updated to 1.12.

**Comment by D3nnis3n** [comment] 2017-10-06 23:36
I saw this is possible by using the enchant "Beheading". Enchants do, unfortunatley, not work on Tinkers Construct Tools. So i would suggest maybe doing one of the following:

1. Config Option for "Beheading" not being needed.
2. Add a Trait / Modifier to Tinker's Construct Tools. You could do that without an hard-dependency.

**Comment by PrinceOfAmber** [comment] 2017-10-07 18:10
Yeah it does kind of suck that tinkers doesnt allow enchants.  I will look into both options a little bit

**Comment by D3nnis3n** [comment] 2017-10-07 18:21
If you could additionally enchant those tools - why would you even Play that game anymore? That would be OP-OP-OP. :D

**Comment by PrinceOfAmber** [comment] 2017-12-27 02:52
I'm just going to close this so I can focus on other content.  Enchant works as intended, and having players drop on every deeath doesnt really fit here, I'm sure other mods exist to do that.

**Closed by PrinceOfAmber** 2017-12-27 02:52 UTC
Labels: mod compatibility, suggestion: new content
