### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1650] opened 2020-12-26 22:15 UTC
Minecraft Version: 1.16.4

Forge Version: 35.1.4

Mod Version: 1.16.4-1.0.0

Single Player or Server: Forge server

Describe problem (what you were doing; what happened; what should have happened): When we placed the cyclic workbench, opened it and the server instantly crashed. (crashing like this every time)

Log file link: https://hastebin.com/onereririr.txt

Crash report link: https://hastebin.com/enotiforov.txt

**Comment by trunksbomb** [comment] 2020-12-26 23:31
Duplicate of #1645 and will be fixed in #1646 when it's merged and released.

**Closed as completed** 2020-12-30 01:11 UTC
Labels: indev, 1.16
