### ISSUE TITLE
1.7.18 Launch Crash

### ISSUE THREAD

**Issue by Coolbro458** [PrinceOfAmber/Cyclic#995] opened 2018-11-23 02:01 UTC
Minecraft version & Mod Version:

1.12.2/Latest Forge/1.17.8

Single player or Server:

Single Player

Describe problem (what you were doing / what happened):
Launching Minecraft

Crash log (if any):
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BaseMetals (BaseMetals-1.12-2.5.0-beta6.280.jar)
  ServerPasswordPlugin (ServerPassword-1.12.2-1.6.8R.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  ItemPatchingLoader (ItemPhysic+Lite+1.3.7+mc1.12.2.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.3.3.ALPHA.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/22/18 7:54 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:529)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:529)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3594621120 bytes (3428 MB) / 6362234880 bytes (6067 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 2 total; -Xmx16G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 Optifine OptiFine_1.12.2_HD_U_E2 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2775.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.5.2775             | forge-1.12.2-14.23.5.2775.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | itemphysic           | 1.4.0                    | minecraft.jar                                 | None                                     |
	| UCHIJA | micdoodlecore        |                          | minecraft.jar                                 | None                                     |
	| UCHIJA | orbis_api            | 1.12.2-1.1.11            | orbis_api-1.12.2-1.1.11.jar                   | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJA | aether               | 1.12.2-1.1.12            | aether_ii-1.12.2-1.1.12.jar                   | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJA | crafttweaker         | 4.1.13                   | CraftTweaker2-1.12-4.1.13.jar                 | None                                     |
	| UCHIJA | mtlib                | 3.0.5                    | MTLib-3.0.5.jar                               | None                                     |
	| UCHIJA | modtweaker           | 4.0.15                   | modtweaker-4.0.15.jar                         | None                                     |
	| UCHIJA | jei                  | 4.13.1.224               | jei_1.12.2-4.13.1.224.jar                     | None                                     |
	| UCHIJA | mantle               | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| UCHIJA | twilightforest       | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
	| UCHIJA | tconstruct           | 1.12.2-2.11.0.106        | TConstruct-1.12.2-2.11.0.106.jar              | None                                     |
	| UCHIJA | basemetals           | 2.5.0-beta6              | BaseMetals-1.12-2.5.0-beta6.280.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | biomesoplenty        | 7.0.1.2402               | BiomesOPlenty-1.12.2-7.0.1.2402-universal.jar | None                                     |
	| UCHIJA | blur                 | 1.0.4-14                 | Blur-1.0.4-14.jar                             | None                                     |
	| UCHIJA | classiccombat        | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                  | None                                     |
	| UCHIJA | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.2.13.jar                    | None                                     |
	| UCHIJA | coroutil             | 1.12.1-1.2.13            | coroutil-1.12.1-1.2.13.jar                    | None                                     |
	| UCHIJA | configmod            | v1.0                     | coroutil-1.12.1-1.2.13.jar                    | None                                     |
	| UCHIJA | cosmiclib            | 0.3.3                    | CosmicLib-1.12.2-0.3.3.ALPHA.jar              | d3974446c00f9f1d275edce305771eeddf30c658 |
	| UCHIJA | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.13.jar                 | None                                     |
	| UCHIJA | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.13.jar                 | None                                     |
	| UCHIJA | cucumber             | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                     | None                                     |
	| UCHIJA | culinaryconstruct    | 1.2.0.1                  | culinaryconstruct-1.2.0.1.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJA | cyclicmagic          | 1.17.8                   | Cyclic-1.12.2-1.17.8.jar                      | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| UCHIJA | dirt2path            | 1.7.1                    | dirt2path-1.8.0.jar                           | None                                     |
	| UCHIJA | dynamictrees         | 1.12.2-0.8.2             | DynamicTrees-1.12.2-0.8.2.jar                 | None                                     |
	| UCHIJA | dynamictreesbop      | 1.12.2-1.3.2             | DynamicTreesBOP-1.12.2-1.3.2.jar              | None                                     |
	| UCHIJA | elevatorid           | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                  | None                                     |
	| UCHIJA | csb_ench_table       | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                | None                                     |
	| UCHIJA | endmetals            | 1.2.0-beta4              | EndMetals-1.12-1.2.0-beta4.53.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | galacticraftcore     | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar         | None                                     |
	| UCHIJA | galacticraftplanets  | 4.0.1.181                | Galacticraft-Planets-1.12.2-4.0.1.181.jar     | None                                     |
	| UCHIJA | mjrlegendslib        | 1.12.2-1.1.6             | MJRLegendsLib-1.12.2-1.1.6.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA | extraplanets         | 1.12.2-0.4.5             | ExtraPlanets-1.12.2-0.4.5.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA | extrautils2          | 1.0                      | extrautils2-1.12-1.9.8.jar                    | None                                     |
	| UCHIJA | gravestone           | 1.10.2                   | gravestone-1.10.2.jar                         | None                                     |
	| UCHIJA | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| UCHIJA | moartinkers          | 0.6.0                    | moartinkers-0.6.0.jar                         | None                                     |
	| UCHIJA | moreplanets          | 2.0.17                   | More-Planets-1.12.2-2.0.17-GC181.jar          | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJA | mysticalagriculture  | 1.6.13                   | MysticalAgriculture-1.12-1.6.13.jar           | None                                     |
	| UCHIJA | mysticalagradditions | 1.2.8                    | mysticalagradditions-1.12-1.2.8.jar           | None                                     |
	| UCHIJA | natura               | 1.12.2-4.3.2.62          | natura-1.12.2-4.3.2.62.jar                    | None                                     |
	| UCHIJA | naturescompass       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
	| UCHIJA | neat                 | 1.4-17                   | Neat+1.4-17.jar                               | None                                     |
	| UCHIJA | nethergoldore        | 1.2.1                    | nethergoldore-1.2.1-mc1.12.x.jar              | None                                     |
	| UCHIJA | nethermetals         | 1.2.0-beta4              | NetherMetals-1.12-1.2.0-beta4.65.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | netherportalfix      | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar             | None                                     |
	| UCHIJA | orespawn             | 3.3.0                    | OreSpawn-1.12-3.3.0.155.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | harvestcraft         | 1.12.2z                  | Pam's+HarvestCraft+1.12.2za.jar               | None                                     |
	| UCHIJA | simplerecipes        | 1.12.2c                  | Pam's+Simple+Recipes+1.12.2c.jar              | None                                     |
	| UCHIJA | simplystrawberries   | 1.12.2-1.0.0             | Pam's+Simply+Strawberries+1.12.2+-+1.0.0.jar  | None                                     |
	| UCHIJA | pamscookables        | 1.1                      | pamscookables-1.1.jar                         | None                                     |
	| UCHIJA | pizzacraft           | 1.3.0                    | PizzaCraft-1.12.2-1.3.0.jar                   | None                                     |
	| UCHIJA | plustic              | 6.5.4.1                  | plustic-6.5.4.1.jar                           | None                                     |
	| UCHIJA | quickleafdecay       | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
	| UCHIJA | sereneseasons        | 1.2.6                    | SereneSeasons-1.12.2-1.2.6-universal.jar      | None                                     |
	| UCHIJA | serverpw             | 1.12.2-1.6.8R            | ServerPassword-1.12.2-1.6.8R.jar              | None                                     |
	| UCHIJA | tickratechanger      | 1.0.14                   | TickrateChanger-1.0.14.jar                    | None                                     |
	| UCHIJA | sleepingoverhaul     | 0.1.2                    | SleepingOverhaul-1.12.2-0.1.2.BETA.jar        | d3974446c00f9f1d275edce305771eeddf30c658 |
	| UCHIJA | snad                 | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                    | None                                     |
	| UCHIJA | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                          | None                                     |
	| UCHIJA | tinkersaddons        | 1.0.7                    | Tinkers'+Addons-1.12.1-1.0.7.jar              | None                                     |
	| UCHIJA | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| UCHIJA | tropicraft           | 7.1.8.105                | tropicraft-MC1.12.2-7.1.8.105.jar             | None                                     |
	| UCHIJA | veinminer            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| UCHIJA | veinminermodsupport  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| UCHIJA | zombieawareness      | 1.12.1-1.11.14           | zombieawareness-1.12.1-1.11.14 (1).jar        | None                                     |

	Loaded coremods (and transformers): 
BaseMetals (BaseMetals-1.12-2.5.0-beta6.280.jar)
  
ServerPasswordPlugin (ServerPassword-1.12.2-1.6.8R.jar)
  de.pt400c.serverpassword.ServerPasswordClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
ItemPatchingLoader (ItemPhysic+Lite+1.3.7+mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.3.3.ALPHA.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.94' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2775
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.19 Extreme
	OpenGlVersion: 4.6.0 NVIDIA 416.94
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

Yes, I am aware I have multiple mods. Have any idea what's wrong?

[crash-2018-11-22_19.54.43-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2609526/crash-2018-11-22_19.54.43-client.txt)

**Comment by josephcsible** [comment] 2018-11-23 02:58
Duplicate of #992

**Closed** 2018-11-23 03:02 UTC
