### ISSUE TITLE
Sack duplication when picking up mana pool

### ISSUE THREAD

**Issue by Lescius** [PrinceOfAmber/Cyclic#543] opened 2017-10-15 02:48 UTC
Minecraft version & Mod Version:

Minecraft 1.12.2
Cyclic 1.12.2-1.9.4
Botania r1.10-349

Single player or Server:

Both

Describe problem (what you were doing / what happened):

Pick up a Botania mana pool with an empty sack of holding. You get a sack containing the pool and also keep the empty sack. The pool will still appear to be on the ground as well, but this is just a visual glitch; you can't interact with it and it will vanish if you reload the world.

**Comment by PrinceOfAmber** [comment] 2017-10-15 23:35
So it sounds like its picking up the pool fine but also somehow failing to delete it . 

Thanks for reporting ill look into it.  Hopefully theres a nice clean fix.

Worst case scenario, if i cant fix it I will add a blacklist so we can block out/disable things that dont work

**Comment by PrinceOfAmber** [comment] 2017-10-16 01:36
Error log when i attempt this 



`[18:35:17] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
        at vazkii.botania.common.block.mana.BlockPool.func_180663_b(BlockPool.java:120) ~[BlockPool.class:?]
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567) ~[axw.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?]
        at net.minecraft.world.World.func_175698_g(World.java:397) ~[amu.class:?]
        at com.lothrazar.cyclicmagic.util.UtilPlaceBlocks.destroyBlock(UtilPlaceBlocks.java:162) ~[UtilPlaceBlocks.class:?]
        at com.lothrazar.cyclicmagic.net.PacketChestSack$1.run(PacketChestSack.java:87) ~[PacketChestSack$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
`

**Comment by PrinceOfAmber** [comment] 2017-10-16 01:54
Ive got it fixed up to the point to where it no longer dupes the empty sack, it consumes it correctly.


 the visual-only glitch still happens however , and it looks like this would be have to fixed on botanias side, AFTER the newest cyclic version comes out that fixes my part.

**Comment by PrinceOfAmber** [comment] 2017-10-16 02:10
https://minecraft.curseforge.com/projects/cyclic/files/2491200

**Closed by PrinceOfAmber** 2017-10-16 02:10 UTC
Labels: bug: gameplay, mod compatibility
