### ISSUE TITLE
[1.15.2] Unable to press the config button in Mods > Cyclic tab.

### ISSUE THREAD

**Issue by 11Rick23** [PrinceOfAmber/Cyclic#1396] opened 2020-04-23 17:46 UTC
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.46

**Mod Version:** 1.15.2-0.3.4

**Single Player or Server:** Single Player

**Describe the problem (what you were doing; what happened; what should have happened):**
The mod probably works all right, except that there's no config in the "Mods" section.
To disable and enable some of the futures, I need the config.
By the way, config files only allowed me to enable/disable some of the items and future.
I'm guessing that the future is not yet supported...

**Log file link:** I don't know what this means. If you need one, please ask me for it.

**Comment by Lothrazar** [comment] 2020-04-25 17:45
duplicate of https://github.com/Lothrazar/Cyclic/issues/1357 so pointing discussion there

**Closed as completed by Lothrazar** 2020-04-25 17:45 UTC
Labels: duplicate, 1.15
