### ISSUE TITLE
Duping glitch (Cyclic automated user, Integrated Dynamics drying basin, evilcraft condensed blood, and hopper)

### ISSUE THREAD

**Issue by Xetaxheb** [PrinceOfAmber/Cyclic#757] opened 2018-03-24 14:59 UTC
x-posted to https://github.com/CyclopsMC/EvilCraft/issues/676 and https://github.com/CyclopsMC/IntegratedDynamics/issues/565
Pack is single player FTB Horizons III

Cyclic-1.12.2-1.10.12.jar
IntegratedDynamics-1.12.2-0.10.3.jar
EvilCraft-1.12.2-0.10.45.jar

Pretty easy reproduce: Auto user with 1 (or more, it will empty down to 1) condensed blood pointing at a drying basin, basin over a hopper pointing at a chest. After it hits 1 blood left, that last blood never disappears but the user keeps putting one in the basin which the hopper also pulls one out of. Infinite item that's otherwise exclusively from dungeon chests.

edit: actually bigger problem I just noticed, anything put in the basin with specific timing while this glitch is going on will just disappear entirely

**Comment by PrinceOfAmber** [comment] 2018-03-24 16:05
I had a report for this very recently  It should be fixed in the lastest version of 1.14.6  that was just released. It was reported to me about the Astral Sorcery Lightwell, but source was in auto user.

https://minecraft.curseforge.com/projects/cyclic/files/2544035

**Comment by Xetaxheb** [comment] 2018-03-24 22:39
Cyclic-1.12.2-1.14.6.jar still has the issue.

**Comment by PrinceOfAmber** [comment] 2018-03-29 06:01
Yep i just confirmed this.

As a test I also wanted to see what happens if i remove the hopper and chest from that equation.  In this case it seems fine

![withouthopper](https://user-images.githubusercontent.com/621529/38072528-948a82ac-32db-11e8-8a6f-106daf07fcf0.gif)

**Comment by PrinceOfAmber** [comment] 2018-03-29 06:04
Once the hopper is added, but the blood stack size is only 1 from the start, bug does not happen 
![onlyone](https://user-images.githubusercontent.com/621529/38072689-61861ee2-32dc-11e8-9b02-106f35776e30.gif)

**Comment by PrinceOfAmber** [comment] 2018-03-29 06:08
This is the actual dupe bug in question: start it with more than one.

What happens here is that when the thing is basin is full up on fluid, it still accepts items.  So now it has full fluid and one item.  

Then two things happen "at the same time" i would say, the user right clicks with a stack of items matching what the basin has, so the basin gives it back for a +1, but also the hopper pulls out that same item as well.

![actualbug](https://user-images.githubusercontent.com/621529/38072802-eb8cb042-32dc-11e8-8613-2258c962ff47.gif)

**Comment by PrinceOfAmber** [comment] 2018-03-29 06:17
User code on my end starts here 

https://github.com/PrinceOfAmber/Cyclic/blob/d4d11ee3d83283d9216b1df6d2efcca45de68b5b/src/main/java/com/lothrazar/cyclicmagic/component/autouser/TileEntityUser.java#L229

"processRightClickBlock" is the main action, the rest are a few alternatives and/or bandaids for certain edge cases.

**Comment by Xetaxheb** [comment] 2018-03-29 16:03
If you turn the speed up with that + symbol you can:
Fill the dryer with 1 blood (instead of 2).
Get dupes with 1 blood.

~~I don't know if this issue is limited to the condensed blood items. I haven't had success testing other random items but I don't know if another mod that has an item that turns into liquid ~~

I tested and a basic single water bucket dupes. No evilcraft involved. @rubensworks

**Comment by Xetaxheb** [comment] 2018-03-29 16:06
At basic "8 speed" putting a mech user against an empty drying basin, putting fuel in the fuel slot, turning it to "always on", and dropping a water bucket in the input slot instantly fills the basin with water, puts an empty bucket in the output, **and then dupes a full water bucket to the output**

**Comment by Xetaxheb** [comment] 2018-03-29 16:27
I haven't done much with MC modding in a few years (so i'm not sure how involved forge's framework is) but..
I would assume somewhere either somebody isn't checking the validity of the operation or is making a tile entity change in world before changing the inventory slot or something to that effect; aka two operations are out of order.

**Comment by PrinceOfAmber** [comment] 2018-03-29 17:06
Thanks for all the great detail.  So the water bucket test was with the same Basin and a user, so just two mods?  

I will try with other fluid containers as well, see if it happens with our without Integrated

**Comment by rubensworks** [comment] 2018-03-31 22:27
FYI, this is the player interaction logic from the ID Drying Basin: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/java/org/cyclops/integrateddynamics/block/BlockDryingBasin.java#L60-L95

This behaviour makes me think that this code is called multiple times by the automated user. But I'm not sure, I haven't had time yet to look into this yet.

**Comment by xBlizzDevious** [comment] 2018-04-05 20:44
Would like to note that it's not restricted to that basin thing.

My friend wanted to set up a supremium watering can (from Mystical Agriculture) on our essence farm. He simply placed the automated user from Cyclic, put the watering can in on "use" mode and watched it duplicate. It was breaking the seeds that it tried to "use" the watering can on, whether directly in front of it or with the auto-user set to a larger area.

This is on ATM3 5.9.1 and that uses Cyclic V1.14.5. Will test with the new version mentioned when I get around to updating my server.

**Comment by PrinceOfAmber** [comment] 2018-04-10 02:44
Thanks for the info with Mystical Ag.

In Cyclic 1.4.7, it does not dupe the can but i do see it breaking the placed seedwhich is weird, that shouldnt happpen. (the original blood version does still happen in 1.4.7)



![watercan](https://user-images.githubusercontent.com/621529/38533497-57f20d86-3c2e-11e8-86e5-f5b5c11e2737.gif)

**Comment by PrinceOfAmber** [comment] 2018-08-04 07:16
This is very stale from old version, Hopefully the blood basin has fixed things on their side by now :) .  If theres anything Cyclic can fix then reopen with new details/steps to reprroduce or a new issue.

**Closed by PrinceOfAmber** 2018-08-04 07:16 UTC
Labels: bug: gameplay, mod compatibility
