### ISSUE TITLE
storage bag delelting items

### ISSUE THREAD

**Issue by IMaFishEatshark** [PrinceOfAmber/Cyclic#1745] opened 2021-02-07 13:19 UTC
Minecraft Version: 1.16.4

Forge Version: 35.1.7

Mod Version: 1.1.5

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
right-clicking a chest goldchest in this case with a Storage bag deletes the content of the bag

Log file link:

Video/images/gifs (direct upload or link):

**Comment by IMaFishEatshark** [comment] 2021-02-07 13:21
Edit: it happens when "deposit mode is set to merge" when you open inventory close it then open the bag it goes haywire

**Comment by IMaFishEatshark** [comment] 2021-02-07 13:22
Edit; when you open the bag close it then open inventory and open the bag it destroys all items

**Comment by IMaFishEatshark** [comment] 2021-02-07 13:24
it seems to only happen in creative mode

**Comment by BlueAgent** [comment] 2021-02-07 14:56
Duplicate of https://github.com/Lothrazar/Cyclic/issues/1659

**Closed as completed** 2021-02-26 21:53 UTC
Labels: 1.16
