### ISSUE TITLE
Crash on placing Diamond Spike on Redstone

### ISSUE THREAD

**Issue by Mystogrigen** [PrinceOfAmber/Cyclic#706] opened 2018-02-28 18:57 UTC
- Minecraft version: 1.12.2
- Forge version: 14.23.2.2611
- Mod version: 1.12.2-1.13.2
- Single player or Server: Single Player

Describe problem (what you were doing / what happened):
Placed a diamond spike on a redstone block.

Crash log (if any):
[Pastebin](https://pastebin.com/8Ean7mB4)

Seems similar to #704

**Comment by PrinceOfAmber** [comment] 2018-03-02 03:51
I can see that you have a crash in the log, but spikes and redstone arent causing it for me.


https://imgur.com/a/utgeL


I think youre right , might be duplicate of #704

**Comment by PrinceOfAmber** [comment] 2018-03-03 02:48
does this happen every time for you? OR did it happen just once and then not again after? @Mystogrigen  

The log just mentions Sound Manager, same log as the 704 but with totally different cause, not making much sense.

**Comment by PrinceOfAmber** [comment] 2018-03-03 05:43
Unconfirmed but possibly caused by something in vanilla https://github.com/MinecraftForge/MinecraftForge/pull/4765

**Comment by Mystogrigen** [comment] 2018-03-03 06:41
@PrinceOfAmber It only happened once.  I spent a little over an hour trying to recreate it thinking it had something to do with the sound muffler from ExUtils2 since I've had a few crashes with it before it was fixed.  Couldn't recreate it though.

Starting to think it could have been any sound that did it, whether it was in-mod or any sound game-wide is a mystery.

**Comment by PrinceOfAmber** [comment] 2018-03-03 07:25
Cool thanks for the update ^^

**Comment by PrinceOfAmber** [comment] 2018-03-03 07:28
IM gonna close this as a duplicate of 704, any updates will be there

**Closed by PrinceOfAmber** 2018-03-03 07:28 UTC
Labels: blame vanilla, bug: crash, cannot replicate
