### ISSUE TITLE
Boomerang breaks Shield projector blocks from rftools

### ISSUE THREAD

**Issue by deevo1** [PrinceOfAmber/Cyclic#1581] opened 2020-11-18 18:56 UTC
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):
Throwing a boomerang at a shield block destroys it, easily poking a hole in it. I know I'm in single player but I'm sure this could happen in multiplayer, I haven't tested that though.

Video/images/gifs (direct upload or link): 
![cyclicbug](https://user-images.githubusercontent.com/74677035/99574702-b94b6200-29a5-11eb-89da-93f51c1437bc.gif)

**Comment by trunksbomb** [comment] 2020-11-23 23:16
Possible duplicate of #1486

**Comment by Lothrazar** [comment] 2021-01-14 06:48
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3074579 or newer

**Closed as completed by Lothrazar** 2021-01-14 06:48 UTC
Labels: old version, 1.12
