### ISSUE TITLE
Ender Wing Prime crash after crash

### ISSUE THREAD

**Issue by HyWhoHuntsBugs** [PrinceOfAmber/Cyclic#558] opened 2017-10-28 02:59 UTC
Minecraft version & Mod Version:
1.12.2, Forge 14.23.0.2515, Cyclic-1.12.2-1.9.6, FTB Horizons 3, MultiMC 0.5.2-1096 (does not auto update)

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
After a crash, frozen instance, or potentially just force-killing an active instance, using an Ender Wing Prime will cause a crash with the attached log.

Crash log (if any):
https://pastebin.com/dpgLmtgW 

Workaround:
Break and replace spawn bed before using the Ender Wing Prime after any sort of crash.

**Comment by PrinceOfAmber** [comment] 2017-10-28 06:15
This is a strange one. So when the force-close or whatever happens, you get back into the game no problem and can run around. Then the crash happens when you use it?  

Could be something wrong with finding or loading players spawn point.  Tried twice to replicate just with alt-f4 force quitting, ill try to dig some more

**Comment by PrinceOfAmber** [comment] 2017-10-28 06:15
DO you know if you were far away from your spawn point? I'm just wondering if it was in an unloaded chunk?

**Comment by HyWhoHuntsBugs** [comment] 2017-10-28 06:23
That's the symptoms exactly, maybe it's only other crashes and softlocks
that causes it. Let me do a bit more reproduction testing. Notably, when I
restart the game, I end up at my bed, so the teleport completes before the
crash. Somehow.

**Comment by PrinceOfAmber** [comment] 2017-10-28 06:29
Yeah its this part that i guess we arent doing the same "After a crash, frozen instance, or potentially just force-killing an active instance, " . im just using windows task manager to end the game

**Comment by HyWhoHuntsBugs** [comment] 2017-10-28 06:34
Ya, I'd only seen it after a crash, let me double-check a normal task manager and multimc kill on my end. If that doesn't work I can certainly cause a real crash.

**Comment by PrinceOfAmber** [comment] 2017-10-28 06:52
Yeah, its a ConcurrentModificationException, those are the hardest to track down because of the threading, and i dont get an exact line number of my code of where it started.

**Comment by HyWhoHuntsBugs** [comment] 2017-10-28 08:40
I had to resort to forcing a crash by way of the IndexOutOfBounds creating chicken-waterfall I use for testing and that doesn't seem to do it. After reloading the game from I was able to Ender Wing back to my bed normally, although unsurprisingly lag-ally, which is a first.

So it's only some crashes.....Of course my other crashes aren't nice enough to leave logs as they tend to hang java completely before I have to force kill them or have the entire system freeze....  *sigh* and this started as a nice reproducible and hopefully easily fixed bug.

Ah well, something to be aware of at least, might as well leave this open in case anyone else encounters it and can provide another data point.

**Comment by PrinceOfAmber** [comment] 2017-10-31 05:27
"Of course my other crashes aren't nice enough to leave logs as they tend to hang java completely before I have to force kill them or have the entire system freeze." I could be totally wrong, there still SHOULD be logs for this, somewhere. There might not be a /crash-log/ but in /logs. it should have something..  it probably renames latest.log to something with a timestamp.

Ill come back to this later, need to find a way to reliably reproduce it

**Comment by PrinceOfAmber** [comment] 2017-12-04 05:07
Closing this issue since it seems like the errors always come from an outside source, and cyclic is only involved indirectly.

**Closed by PrinceOfAmber** 2017-12-04 05:07 UTC
Labels: 1.12, bug: crash, Cannot Replicate, mod compatibility
