### ISSUE TITLE
Crash whilst initializing game

### ISSUE THREAD

**Issue by JaxTheWolf** [PrinceOfAmber/Cyclic#417] opened 2017-06-29 10:49 UTC
I hope that this issue will be fixed ASAP, because it is quite annoying.

Details:

MC version: 1.12 with Forge .2387
Crash: https://pastebin.com/jYxENy1c

-Jax

**Comment by PrinceOfAmber** [comment] 2017-06-29 14:48
Yep all 1.12 mods are going to run into this.  forge 2347 is the last version compatible , after that forge broke the registry system and made it in a different way , so all mods have to update to fix it.  I hope to get this done today, but im  going away for the weekend so it might be a bit late.

References
https://github.com/PrinceOfAmber/Storage-Network/issues/11
https://twitter.com/lothrazar/status/879228787258408960
https://twitter.com/modmuss50/status/878387667678806017

**Comment by PrinceOfAmber** [comment] 2017-06-29 14:51
Duplicate of this issue, not fixed yet but as i said i hope soon.


keep an eye out there for fixes.  https://github.com/PrinceOfAmber/Cyclic/issues/416

**Closed by PrinceOfAmber** 2017-06-29 14:51 UTC
Labels: 1.12, blame forge, bug: crash, duplicate

**Comment by PrinceOfAmber** [comment] 2017-06-30 04:01
Fixed version is up https://minecraft.curseforge.com/projects/cyclic/files/2443647 .

There could be other little issues but at least my server starts up and all the stuff is there.
