### ISSUE TITLE
Uncrafting Grinder causing crash

### ISSUE THREAD

**Issue by Miner94** [PrinceOfAmber/Cyclic#704] opened 2018-02-25 07:19 UTC
Minecraft version & Mod Version:
1.12.2 mod version is 1.13.2

Single player or Server: This is in Single player

Describe problem (what you were doing / what happened): I am running uncrafting Grinder and after a few uncrafts the game Crashes

Crash log (if any): https://pastebin.com/LeZWGYgd

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment] 2018-03-02 03:55
When i look in the log file i dont see anything pointing at Cyclic.  

So i try to replicate the issue on my own anyway just in case.

![uncr](https://user-images.githubusercontent.com/621529/36882744-7ee6356a-1d8a-11e8-91f5-8312f9c349c5.gif)


Gif shows it working for me.  So if its an issue i need more information I guess.  What items were you uncrafting?  Maybe the specific item is relevant.

**Comment by PrinceOfAmber** [comment] 2018-03-03 02:47
(deleted my previous comment.

Yeah both #706  and this have a near identical crash log that mentiones "net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:252)"

, entire crash log is vanilla code error about playing sounds.

And when I try to replicate both (uncrafting or using spikes) no issues.  so i dont know whats going on i have to play around with it a bit.


@Miner94  does this happen every time for you? OR did it happen just once and then not again after

**Comment by PrinceOfAmber** [comment] 2018-03-03 05:43
Unconfirmed but possibly caused by something in vanilla https://github.com/MinecraftForge/MinecraftForge/pull/4765

**Comment by PrinceOfAmber** [comment] 2018-03-03 07:30
I will leave this OPEN for now, until 

- new information comes up with something I can fix on my end, (in which case ill remove the 'blame vanilla' tag)
- More information comes into that Forge PR link, (it will either get merged or it will at least get new information)

**Comment by PrinceOfAmber** [comment] 2018-03-21 06:07
I still think the 'blame vanilla' tag is valid. but also This fix coming soon in 1.14.5 might be related. either way this is good to go https://github.com/PrinceOfAmber/Cyclic/commit/6ffe6f449c89119ce4bcdf19da08e60f27eae9e3

**Closed by PrinceOfAmber** 2018-03-21 06:07 UTC
Labels: blame vanilla, bug: gameplay, done [pending release]
