### ISSUE TITLE
Harvester not harvesting Resynth Plants.

### ISSUE THREAD

**Issue by smallerYeet** [PrinceOfAmber/Cyclic#1608] opened 2020-12-03 00:20 UTC
Minecraft Version:  1.16.3

Forge Version: 34.1.42

Mod Version: 0.9.3

Single Player or Server: Playing on Server

Describe problem (what you were doing; what happened; what should have happened):
Harvester not harvesting Resynth Plants. They just are not harvested, nothing else.

Video/images/gifs (direct upload or link): 
https://imgur.com/a/Meeqw2E

**Comment by trunksbomb** [comment] 2020-12-03 00:40
Not sure what a Resynth plant is, what mod is that from?

**Comment by smallerYeet** [comment] 2020-12-03 00:42
https://www.curseforge.com/minecraft/mc-mods/resynth/
This is the mod

**Comment by trunksbomb** [comment] 2020-12-03 00:52
Very likely a duplicate of #1600 and resolved in PR #1603 (not yet published). See comments on those two for details on the problem and fix.

**Comment by smallerYeet** [comment] 2020-12-03 01:03
So I have to wait?

**Comment by trunksbomb** [comment] 2020-12-03 01:51
Until the fix is published, yes. If you're playing single player (ie don't have to worry about other people) then I suppose you could compile the mod yourself but that's a lot of work instead of just waiting -- the mod author is usually quick with releases.

**Comment by smallerYeet** [comment] 2020-12-03 02:55
Okay thanks then, ill wait till the release

**Comment by Lothrazar** [comment] 2020-12-03 21:04
All vanilla and almost every mods use an "age" property for their block-state growth stages . luckily its open source so i can see that they arbitrarily use "growth_stage" for some reason 
https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/blob/a9f47439d103c1c17ca7a4ffd05c2dc0397e5e5f/src/main/java/com/ki11erwolf/resynth/plant/block/BlockBiochemicalPlant.java#L59

**Closed as completed** 2020-12-04 07:47 UTC
Labels: compatibility, indev, 1.16
