### ISSUE TITLE
Console spam (extended inventory crashes when saving player names with special characters)

### ISSUE THREAD

**Issue by OGTEnzoHD** [PrinceOfAmber/Cyclic#188] opened 2016-11-28 14:16 UTC
hello seem to be having a console spam on hermitpack v1.4.0 that includes cyclic v1.8.2 in console constantly getting

28.11 15:09:07 [Server] Server thread/ERROR [cyclicmagic]: Could not save file for player [Owner]< BlaizeHD
28.11 15:09:07 [Server] Server thread/INFO [STDERR]: [com.lothrazar.cyclicmagic.util.UtilPlayerInventoryFilestorage:savePlayerItems:136]: java.io.FileNotFoundException: .\world\playerdata\_[Owner]< BlaizeHD.invo (The filename, directory name, or volume label syntax is incorrect)

this is not just for this player but for multiple players.

at the moment is just seems like console spam will update if it turns out to effect server negatively
thanks

**Comment by PrinceOfAmber** [comment] 2016-11-29 02:49
This should only get logged out if the Inventory Upgrade failed to save.  Have you noticed any players losing items or complaining about problems with that?

**Comment by PrinceOfAmber** [comment] 2016-11-29 06:31
Yeah, keep me updated.

Also do you know any context, such as does it happen the first time the player joins the server? maybe changing dimensions? something like that?

**Comment by OGTEnzoHD** [comment] 2016-11-29 11:46
turns out it possibly is causing some inconvenience.
Players have been saying items have disappeared from there inventory, if they re-login sometimes they will get those items back. As for when the player logs in ill keep an eye out when it it next happens but i have tried logging in in all dimensions and cannot recreate it.

**Comment by PrinceOfAmber** [comment] 2016-12-02 08:40
Ill look into this as much as I can.  I do play on two servers right now, one is using the Hermitpack modpack.  with a custom home server and one is the Hyperantix modpack on creeperhost.  We havent seen any issues or item loss yet, but that doesnt mean im dismissing the issue.

Basically what happens is the server creates custom files on the server harddrive, similar to the player.dat files only a bit different.  

If you look in your world you will have a "playerdata" folder, and inside of that you will have for each player a .invo file and a .backup.  It sounds like what happens is that it has an error loading the regular.invo file (which is where the player see items dissapearing), then at a later time cyclic tries to fix itself and loads the .backup file , which as you said sometimes they get items back.

The files are only a few kilobytes in size, so size shouldnt be a factor, and OS write permissions shouldnt be either.

**Comment by Morpheus1101** [comment] 2016-12-27 04:35
On a different note but still server console spam on the MMD-Dev server i noticed this:

https://puu.sh/t2bSE/a0a6111d75.txt

**Comment by PrinceOfAmber** [comment] 2016-12-29 02:13
@Morpheus1101  this looks like an unrelated issue. bug from OP is saving extended inventories items, your log is about editing signs on click

Caused by: java.lang.NoSuchMethodError: net.minecraft.tileentity.TileEntitySign.func_145913_a(Z)V
at com.lothrazar.cyclicmagic.module.PlayerAbilitiesModule.onLeftClickBlock(PlayerAbilitiesModule.java:203) ~[PlayerAbilitiesModule.class:?]

**Comment by PrinceOfAmber** [comment] 2016-12-29 02:31
@OGTEnzoHD  i found the cause for this. im using the player display name as a filename to save this data, (so player.getDisplayNameString() ), but based on the log, the players display name on your server is

[Owner]< BlaizeHD

so the owner tag and the '<' is included in the name, which cant be used in a file. ill have to filter out these special characters first and that should solve it

**Comment by PrinceOfAmber** [comment] 2016-12-29 16:29
Fixed in 1.9.9 https://minecraft.curseforge.com/projects/cyclic/files/2361605

Im 90% sure i got what was causing this, so let me know if anything like it happens again.

**Closed by PrinceOfAmber** 2016-12-29 16:29 UTC
Labels: bug, compatibility

**Comment by MabaKalox** [comment] 2020-07-15 18:48
Got same error, on last sky factory 4 modpack. The Melter while producing fluid exp spam this in server logs.
[22:32:40] [Server thread/ERROR] [cyclicmagic]: true fluidAllowed
