### ISSUE TITLE
Everything in my storage bag went missing

### ISSUE THREAD

**Issue by NordicGamerFE** [PrinceOfAmber/Cyclic#1954] opened 2021-10-28 19:59 UTC
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.8

Single Player or Server: Server [SP not tested]

Modpack: AffectCraft SMP

Describe problem (what you were doing; what happened; what should have happened):
I've got no idea how or why but when I switched gamemodes everything in my storage bag went missing I cant reproduce the issue I am just posting so its on your radar and others can add to it

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment] 2021-11-03 16:02
yeah theres a long standing vanillla (and/or forge) bug where items in creative can get their data wiped. since in mojang world the client 'takes over' in creative or so im told.

 There is a known fix, kinda, but the fix would change how storage worked meaning updating the mod would make bags start over.  
 
 Duplicate of https://github.com/Lothrazar/Cyclic/issues/1886 so more follow up will be there

**Closed as completed by Lothrazar** 2021-11-03 16:02 UTC
Labels: duplicate, 1.16
