### ISSUE TITLE
Speed Charm has infinite power

### ISSUE THREAD

**Issue by Shadows-of-Fire** [PrinceOfAmber/Cyclic#211] opened 2016-12-23 21:51 UTC
So this is quite the odd issue, the Speed Charm has the ability to refresh its durability bar by simply moving the ItemStack. 

All the same, the 32 durability it has is an extremely low number, so if/when you fix this, consider pushing that up.  An emerald for 13 seconds of speed from that charm is a little pricey.

Using Cyclic-1.10.2-1.9.4.jar

**Comment by Shadows-of-Fire** [comment] 2016-12-23 22:19
Alright now its randomly stopped being able to do that, after going into a boat.  But now it permanently drains, which is making it useless.

**Comment by PrinceOfAmber** [comment] 2016-12-24 04:10
Yeah, it should stay empty when it runs out.

**Comment by Shadows-of-Fire** [comment] 2016-12-24 04:24
So the one that went useless stayed useless, but I found another one and the bug is there again.

**Comment by PrinceOfAmber** [comment] 2016-12-24 04:54
I found the cause. its only updating the durability on the clientside, not server, so when it updates the server value is treated as truth (happens on single player too same logic).  fix coming tonight.

**Comment by Shadows-of-Fire** [comment] 2016-12-24 07:39
You sure you don't want to increase the durability of it? It literally runs out in 13 seconds.

**Comment by PrinceOfAmber** [comment] 2016-12-24 16:42
Yes, I also increased durability to 2000 while fixing this.  released in 1.9.5 https://minecraft.curseforge.com/projects/cyclic/files/2359852

**Closed by PrinceOfAmber** 2016-12-24 16:42 UTC
Labels: bug
