### ISSUE TITLE
PacketSwapBlock#onMessage modifies the world asychronously

### ISSUE THREAD

**Issue by Aaron1011** [PrinceOfAmber/Cyclic#143] opened 2016-10-30 18:26 UTC
The packet handler PacketSwapBlock#onMessage is [modifying the world](https://github.com/PrinceOfAmber/Cyclic/blob/39a6304/src/main/java/com/lothrazar/cyclicmagic/net/PacketSwapBlock.java#L184) directly from the handler method. Since this method is called from a Netty thread, the world is being modified asynchronously, causing problems with both Vanilla and other mods.

I recommend running this handler on the main thread, using `MinecraftServer#addScheduledTask`

**Comment by mbax** [comment] 2016-10-30 23:26
Put the entire handling section, not just the spot @Aaron1011 highlighted, into a main thread handler. You have several calls in there that could result in unpleasant or unexpected behavior.

**Comment by PrinceOfAmber** [comment] 2016-11-01 00:55
Good catch.

Yeah i have also had crashes with this item where it causes ConcurrentModificationException, ive been meaning to find a solution for this.

**Comment by PrinceOfAmber** [comment] 2016-11-01 01:27
Would it help if i avoided the setBlockToAir, and just did a setBlockState to overwrite?

Ill add a scheduled task anyway

**Comment by PrinceOfAmber** [comment] 2016-11-01 01:30
See the referenced commit for the code changes , i think this follows your idea

`  @Override
  public IMessage onMessage(PacketSwapBlock message, MessageContext ctx) {
    if (ctx.side.isServer() && message != null && message.pos != null) {
      MinecraftServer s = FMLCommonHandler.instance().getMinecraftServerInstance();//ctx.getServerHandler().getNetworkManager().get
   
      // MinecraftServer.getServer().//doesnt exist anymore
      if(s == null){
        handle(message,ctx);
      }
      else{
        s.addScheduledTask(() -> handle(message, ctx)); // all block changes
      }
      
    }
    return null;
  }`


Ill do some testing and tidy up the code, maybe release tonight or tomorrow

**Comment by mbax** [comment] 2016-11-01 01:31
Other spots like dropBlockAsItem are also problematic. As are potentially calls that get blocks too, as they can potentially cause chunk loading. Also, you probably don't need that concurrent modification exception catch. :3

**Comment by PrinceOfAmber** [comment] 2016-11-01 03:48
yeah it didnt catch anything anyway because of async nature :P i learned that the hard way

**Comment by PrinceOfAmber** [comment] 2016-11-01 05:32
Thanks a lot for the code advice, i didn't know about the addScheduledTask before.

This should be fixed in build 1.7.22 https://minecraft.curseforge.com/projects/cyclic/files/2340924

I thought about doing this to every single network packet, but im not sure if that is a good idea?  I would love any other advice you have to improve things here.  

For getblocks, that only happens when a player uses an item, so it SHOULD be on a loaded chunk. or if a tile entity is running update() , also loaded chunk.

**Closed by PrinceOfAmber** 2016-11-01 05:32 UTC
Labels: bug

**Comment by mbax** [comment] 2016-11-01 12:44
If you're modifying the world in any way, you should be doing that from the main server thread. Also if iterating, or making any calls that might trigger loading any entities/tileentities.
