### ISSUE TITLE
Fluid Null Pointer

### ISSUE THREAD

**Issue by Seth0067** [PrinceOfAmber/Cyclic#458] opened 2017-07-26 00:36 UTC
Minecraft version & Mod Version:
1.12 minecraft w/ cyclic 1.7.0

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Crash on startup

Crash log (if any):
[Paste](https://pastebin.com/PST36K4s)

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

--Hope this is useful!!

**Comment by PrinceOfAmber** [comment] 2017-07-26 02:21
Yep thanks for the crash log, always useful.  

 duplicate of #453 . conflict is because poison is already added by biomes o plenty first, and then im adding a recipe for a Poison Bucket in an unsafe way. Fix coming soon in 1.7.1

**Closed by PrinceOfAmber** 2017-07-26 02:21 UTC
