### ISSUE TITLE
Excavate enchant crashes server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PrinceOfAmber/Cyclic#1583] opened 2020-11-19 21:58 UTC
Minecraft: 1.16.4
Forge: 35.0.17
Cyclic: 1.16.3-0.9.2

Single Player or Server: **Server**

Describe the problem (what you were doing; what happened; what should have happened):

In my modpack, [Survival in Chaos](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos), when trying to mine Silent Gear Azure Silver with a Silent Gems Aquamarine pickaxe with the Cyclic Excavate enchantment it will crash our server. I have tested this on our test and production servers. If I use a Cyclic pickaxe, then it works fine.

We also have FTB Ultimine in the pack.

Log file link:

[crash-2020-11-19_14.47.23-server.txt](https://github.com/Lothrazar/Cyclic/files/5569947/crash-2020-11-19_14.47.23-server.txt)

Please note over 1,000 lines of text in the crash report stating:
`at com.lothrazar.cyclic.enchant.EnchantExcavation.harvestSurrounding(EnchantExcavation.java:156) ~[cyclic:1.16.3-0.9.2] {re:classloading}`

**Comment by trunksbomb** [comment] 2020-11-23 23:18
Possible duplicate of #1575 and #1455 (unable to replicate)

**Comment by trunksbomb** [comment] 2020-11-24 01:15
I figured it out thanks to your description.

The Aquamarine pickaxe is not capable of harvesting Silent Gear's Azure Silver ore, so when it's looking for surrounding blocks it just keeps finding the same ones over and over again (see https://github.com/Lothrazar/Cyclic/issues/1455#issuecomment-719883033) and getting stuck in a loop.

You can replicate this by putting the enchantment on a Stone Pickaxe and trying to mine 2 Gold Ores adjacent to one another.

I'll be submitting a PR in just a few minutes with the fix.

**Closed as completed** 2020-11-24 15:09 UTC
Labels: 1.16
