### ISSUE TITLE
Flower Cyan configuredfeature is not registered

### ISSUE THREAD

**Issue by TelepathicGrunt** [PrinceOfAmber/Cyclic#1607] opened 2020-12-02 15:22 UTC
Hello! I was test running my mod called Blame with a bunch of mods and it seemed to have found that cyclic does not register the ConfiguredFeatures form of flower_cyan. This can be an issue for mod compatibility as under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

By that I mean, if mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95459000-ff41ee80-0940-11eb-8569-52a2be15cc4d.png)

Specifically, when you call .withConfiguration on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldgenRegisties at mod init (you can do it in FMLCommonSetupEvent so you have your config ready too if it is needed). 

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/a4e3365e3867b8510952ebf658c415de6e412927/src/main/java/com/telepathicgrunt/repurposedstructures/RSConfiguredFeatures.java#L184-L185

I hope this helps!

**Comment by trunksbomb** [comment] 2020-12-03 00:08
Duplicate of #1543 but we should have enough information now to resolve.

**Comment by Lothrazar** [comment] 2020-12-03 17:48
Thanks for the link to the sample.

Forge has zero documentation for this, becuase of course https://mcforge.readthedocs.io/en/1.16.x/search.html?q=feature

**Closed as completed** 2020-12-03 22:18 UTC
Labels: duplicate, indev, 1.16
