### ISSUE TITLE
Unable to play multiplayer with beta 1.1.3

### ISSUE THREAD

**Issue by Letoric** [PrinceOfAmber/Cyclic#1724] opened 2021-01-24 14:56 UTC
Minecraft Version: 1.16.5

Forge Version: 36.0.1

Mod Version: 1.1.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Attempt to connect, get an NPE and it disconnects you, but does not hard crash the server. This is reproducible with only Cyclic loaded.

Error:
[24Jan2021 08:49:54.935] [Netty Server IO #2/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
[24Jan2021 08:49:55.016] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Letoric lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by Lothrazar** [comment] 2021-01-25 17:32
Found root cause https://github.com/Lothrazar/Cyclic/commit/fa88f3f58c8f38c1765a65871bcfb891016b5260#diff-47d9d64f34439f313286b5440c4b6fdf171e5b8e6360ef585a88a82bedfa5852R185  
was an attempt to resolve https://github.com/Lothrazar/Cyclic/issues/1659 . Fix on the way

**Comment by Lothrazar** [comment] 2021-01-25 17:40
Also dupe of https://github.com/Lothrazar/Cyclic/issues/1704

**Closed as completed** 2021-02-01 01:31 UTC
Labels: indev, 1.16
