### ISSUE TITLE
v0.9.3 - Monster Ball deletes captured villager that was sleeping.

### ISSUE THREAD

**Issue by ariosos** [PrinceOfAmber/Cyclic#1599] opened 2020-11-28 21:08 UTC
I'm playing with ATM6, and I captured a sleeping (leatherworker) villager with the monster ball. First thing I noticed, the bed said "still occupied" (until broken and placed back down). I headed back to my base (some 800 blocks away - chunks were unloaded), and tried to release the villager. The ball vanished, and there was no villager.

**Comment by trunksbomb** [comment] 2020-12-01 02:06
I was able to replicate this behavior. What's happening is that we're removing the villager from the bed without 1) updating the bed to not be occupied and 2) updating the villager to set it to not be asleep. What the monster ball does, essentially, is save the state the entity was in at the time of capture (same effect as saving/closing the game, or moving away from the chunk it's in). Then, when placing it back into the world, it "loads" the entity into the world and updates its position to be wherever you clicked.

The problem is that when a Villager is sleeping, it's returned to its sleeping location instead. I can't say for sure that your villager returned to its village because you were so far away, but if you were to release a sleeping villager near its bed you'd see it get back in said bed.

**Comment by ariosos** [comment] 2020-12-01 02:20
That's what I figured - probably tried to go back to the chunk it was in (I recall hearing about a similar bug with vanishing villagers in 1.12 or 1.10). Crazy chunk-related glitches. :) I even went back to the house I nabbed the villager from, and didn't see it there (unless the villager ran off somewhere).

**Comment by trunksbomb** [comment] 2020-12-01 02:34
Since the village wasn't loaded when you released the sleeping villager, I think it got "stuck" in limbo. I wonder if you were to chunk load the chunk where you released the villager, then head back to the village -- would he appear? I bet he would.

You would either need a second account to assist with this, or a mod that adds a chunk loader.

Either way, my PR fixes this issue by first waking up an entity before capturing it.

**Comment by trunksbomb** [comment] 2020-12-01 03:10
Here's a funny side effect of releasing that sleeping villager:

![cyclic_harvesterwhat](https://user-images.githubusercontent.com/1904331/100692376-b747b280-3358-11eb-9153-22846df4b648.gif)

**Closed as completed** 2020-12-04 07:47 UTC
Labels: indev, 1.16
