### ISSUE TITLE
Endlessly increasing health bar when changing dimensions

### ISSUE THREAD

**Issue by TrueGkoliver** [PrinceOfAmber/Cyclic#1441] opened 2020-06-10 21:11 UTC
Minecraft Version: 1.15.2

Forge Version: 31.2.9

Mod Version: 1.15.2-0.4.1

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
After getting all heart levels with Spice of Life; carrot edition (20 extra HP; one extra HP bar), going out of the End increases my health 1 bar (+20 hp) There seems to be no limit to this. This happens regardless of whether or not heart containers are disabled, and even deleting the Cyclic Health Modifier from the level.dat does nothing, because it just comes back the next time I go out of the End.

Log file link (forced crash): https://pastebin.com/BvN073bf

Video: https://www.youtube.com/watch?v=w7t29vPaP0E&feature=youtu.be (Note: I'm using Mantle so all the bars are stacked, so my health goes from 3 bars max to 4 bars max)

**Comment by ghost** [comment] 2020-06-11 08:50
probably related to #1418

**Comment by Lothrazar** [comment] 2020-06-21 07:14
Yep duplicate of #1418 which has a fix coming

**Closed as completed by Lothrazar** 2020-06-21 07:14 UTC
Labels: duplicate, 1.15
