### ISSUE TITLE
Crash While Attempting to Clear Crafting Grid in Cyclic Crafting Table

### ISSUE THREAD

**Issue by DizzyDJW** [PrinceOfAmber/Cyclic#1673] opened 2021-01-07 23:57 UTC
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 1.0.1

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened): Attempted to clear the crafting grid on the Cyclic workbench via the GUI button and crashed. "Exception in server tick loop"
It was supposed to simply return the items in the grid to my inventory, there was more than enough room.

Log file link: https://pastebin.com/0iYkANAk

**Comment by Lothrazar** [comment] 2021-01-08 02:39
Latest version has a fix released in 1.0.2  :)  Thanks for the report anyway . dupe of https://github.com/Lothrazar/Cyclic/issues/1652

**Closed as completed by Lothrazar** 2021-01-08 02:39 UTC
Labels: duplicate
