### ISSUE TITLE
Hydrator input slot bug (1.12)

### ISSUE THREAD

**Issue by qooq8poop** [PrinceOfAmber/Cyclic#1728] opened 2021-01-27 18:23 UTC
Minecraft Version: 

Forge Version: 

Mod Version: 

Single Player or Server: Server

Describe the problem (what you were doing; what happened; what should have happened):
I have been using the hydrator to turn concrete powder into concrete. When there are items in an input slot that is not the top left, the machine stops working. If those items are taken out and there is only one stack in the top left input, the machine works again.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment] 2021-01-30 21:04
What  version of the mod are you using?

What modpack are you using

This was working as intended last time i checked in sky factory 4 and sevtech ages

**Comment by qooq8poop** [comment] 2021-01-31 23:55
I was using Cyclic-1.12.2-1.19.18 in MC Eternal. This was on a server.

**Comment by Lothrazar** [comment] 2021-04-16 21:24
yeah this is just the way it is in 1.12. works on exact match of the 2x2 area just like a recipe system. gif of it working like that with unlocked slots, you have to clear it out. or send items slower. also could use lock button which sometimes works.  Since the player can sort it out in game im going to leave 1.12 as-is 
![1728](https://user-images.githubusercontent.com/621529/115085454-6c6da800-9ebf-11eb-993e-db26b0cf88ed.gif)
for this feature

**Closed as completed by Lothrazar** 2021-04-16 21:24 UTC
Labels: working as intended, old version, 1.12
