### ISSUE TITLE
Solid Ender Eye doesn't work

### ISSUE THREAD

**Issue by BugmanBugman** [PrinceOfAmber/Cyclic#1609] opened 2020-12-04 05:22 UTC
Minecraft Version:  1.16.4

Forge Version: 35.1.7

Mod Version: 0.9.3

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

Solid Ender Eye doesn't activate when you right click it. in the video, I compared it to the ender eye.

Video/images/gifs (direct upload or link): 
https://streamable.com/xw52vx

**Comment by trunksbomb** [comment] 2020-12-04 05:38
Duplicate of #1517 with lots of information there.

tl;dr: Can't replicate when Cyclic is the only mod present. Are you playing in a mod pack?

**Comment by BugmanBugman** [comment] 2020-12-04 05:45
Ah ok, I’ll do some binary searching tmrw and get back to you. I have a feeling what mod it is though

**Closed as completed** 2020-12-04 18:44 UTC
Labels: duplicate
