### ISSUE TITLE
1.16.4 server crash on single player 

### ISSUE THREAD

**Issue by 5kedone** [PrinceOfAmber/Cyclic#1569] opened 2020-11-09 07:27 UTC
Minecraft Version: 1.16.4

Forge Version: 35.0.7

Mod Version: 0.9.1

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):

When you die you get a hard crash that only gen a server crash log , latest log linked 

Log file link:
https://paste.gg/p/anonymous/fff97e2d9bc04b66a5bae3a1204a565e

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by 3x1at1on** [comment] 2020-11-09 08:54
Potentially duplicate of #1567 #1563 #1572 #1571 
I have feeling this is something to do with one of the these commits
 https://github.com/Lothrazar/Cyclic/commit/4b0cf218fa256cededf379184f985413621935b0
https://github.com/Lothrazar/Cyclic/commit/4a73aae563661b5635221cf159c6d48b9d05a360
https://github.com/Lothrazar/Cyclic/commit/ec55fcf27740f53e2cafc6bd26fc153d8f17b8e7

**Comment by Grant-K** [comment] 2020-11-09 17:46
I have the same issue on a  server anytime a player dies it causes a ticking entity event crash on the mob that slayed them here is two crash reports 1 from a endermen killing a player 1 from an ice and fire ghost:
[crash-2020-11-09_03.54.17-server.txt](https://github.com/Lothrazar/Cyclic/files/5512349/crash-2020-11-09_03.54.17-server.txt)
[crash-2020-11-09_17.22.09-server.txt](https://github.com/Lothrazar/Cyclic/files/5512350/crash-2020-11-09_17.22.09-server.txt)

**Comment by Lothrazar** [comment] 2020-11-11 02:00
yep. that is correct  3x1at1on  . 0.9.2 coming out tonight

**Closed as completed by Lothrazar** 2020-11-11 02:00 UTC
Labels: 1.16

**Comment by 5kedone** [comment] 2020-11-11 07:55
Thankyou for the fix good sir all seems to be working now I'm my test setup woohoo
