### ISSUE TITLE
[1.16.5] Ethereal Circlet does not prevent "damage" on the MekaSuit

### ISSUE THREAD

**Issue by Ashetf2** [PrinceOfAmber/Cyclic#2108] opened 2022-05-23 23:07 UTC
Minecraft Version: 1.16.5

Forge Version: 36.2.31

Mod Version: 1.5.15

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
The Ethereal Circlet, that prevents elytra crash damage, does not prevent MekaSuit from Mekanism to "absorb" the crash damage, causing it consume energy.

Log file link:
No log apparently associated with these actions.

Video/images/gifs (direct upload or link): 
https://youtu.be/GZttXudYVCI

**Comment by Lothrazar** [comment] 2022-06-28 22:05
Yeah, this is probably working as intended. 
Possibly a bug that can be fixed on mekanisms side.

The charm affects all damage of type IN_WALL or FLY_INTO_WALL https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/event/ItemEvents.java#L217
And then here  i cancel the event.
https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/event/ItemEvents.java#L132
So as long as the Ethereal Circlet is taking durability damage, the event is being cancelled.

Im not sure how Mekanism works but i assume their armor consumes based on this event even though i cancelled it?  
Sorry i dont have an easy fix.

**Closed as completed by Lothrazar** 2022-06-28 22:05 UTC
Labels: CausedByOthermod, 1.16
